version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - .:/var/www/html/wp-content/themes/wp-theme/
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 81:80
    environment:
      PMA_HOST: mysql
      PMA_USERNAME: root
      PMA_PASSWORD: example
